# Generated by Django 3.1.6 on 2021-02-04 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210203_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=7),
            preserve_default=False,
        ),
    ]
