# Generated by Django 3.1.6 on 2021-02-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_image_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='price',
        ),
    ]
